name: "Export to itch.io after publishing a release"
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  itch-export:
    runs-on: ubuntu-latest
    steps:
      - name: Get release zip
        run: |
          sudo apt update
          sudo apt install -y curl
          curl -LO $(curl -s https://api.github.com/repos/xstron/PSGJ15/releases/latest | grep "browser_download_url.*\.zip" | cut -d : -f 2,3 | tr -d \")

      - name: Export to itch
        uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: web
          ITCH_GAME: a-title-that-incorporates-neither-shadows-nor-alchemy
          ITCH_USER: beyondredacted
          PACKAGE: release.zip
